### ISSUE TITLE
Create a critique of another group's website by answering the following questions: 

### ISSUE THREAD

**Issue by zjgoodman** [zjg95/cs373-idb#77]
```
What did they do well?
What did we learn from their website?
What can they do better?
What puzzles us about their website?
```

**Comment by sdragoon** [comment]
(only close once added to presentation)
For use in presentation:

What did they do well?
Most of the pages are very aesthetically pleasing, with a good background image and clean formatting. Specific pages also present a fair amount of information in a condensed space. Sliding images and integration of Google Maps is also a nice touch.
List format:
-aesthetically pleasing
-good backgrounds
-clean formatting
-good info/space ratio
-sliding images
-Google Maps integration
-nice About page

What did we learn from their website? (NEEDS BETTER ANSWER)
That good aesthetics can go a long way on a website that seems to be currently lacking in the data department.

What can they do better?
-Add more pets to each shelters page, perhaps using the same sliding images scheme they use for pet-specific pages.
-More info in general, tables they have seem to have a good setup to hold more data but data isn't there.
-Consistency between the pages of each model (Shelters has a good image and sidebar added while pets and cities just has a table), they look good on their own but together the overall effect is hurt.
-If possible, make age column on pets pet actually sort by relative age instead of alphabetically, so that it goes Senior, Adult, Young instead of Adult, Senior, Young. 

What puzzles us about their website?
-While the cities table seems to have very good info on it, like a vet, park, and groomer. It does not contain a direct link to the shelters they have included (or at least not an obvious one). It would be a nice touch if someone could navigate to the shelters from cities table without having to directly click on city
